apiVersion: v1
imagePullSecrets:
- name: ig003-service-account-dockercfg-kd58d
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"maistra.io/mesh-generation":"2.6.9-1-172"},"labels":{"app":"ig003","app.kubernetes.io/component":"istio-ingress","app.kubernetes.io/instance":"istio-system","app.kubernetes.io/managed-by":"maistra-istio-operator","app.kubernetes.io/name":"istio-ingress","app.kubernetes.io/part-of":"istio","app.kubernetes.io/version":"2.6.9-1-172","istio":"ingressgateway","istio.io/rev":"app-mesh-01","maistra-version":"2.6.9","maistra.io/owner":"istio-system","maistra.io/owner-name":"app-mesh-01","release":"istio"},"name":"ig003-service-account","namespace":"lbg-ocp-bookinfo-300-prod"}}

      '
    maistra.io/mesh-generation: 2.6.9-1-172
    meta.helm.sh/release-name: service-mesh-injected-gateway
    meta.helm.sh/release-namespace: istio-system
    openshift.io/internal-registry-pull-secret-ref: ig003-service-account-dockercfg-kd58d
  creationTimestamp: '2025-09-17T08:27:26Z'
  labels:
    app: ig003
    app.kubernetes.io/component: istio-ingress
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: istio-ingress
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 2.6.9-1-234
    istio: ingressgateway
    istio.io/rev: app-mesh-01
    maistra-version: 2.6.9
    maistra.io/owner: istio-system
    maistra.io/owner-name: app-mesh-01
    release: istio
  name: ig003-service-account
  namespace: lbg-ocp-bookinfo-300-prod
  resourceVersion: '291679214'
  uid: 177437f8-c842-4d83-b18d-7d50bea7e8d5
secrets:
- name: ig003-service-account-dockercfg-kd58d
