apiVersion: v1
imagePullSecrets:
- name: ig001-service-account-dockercfg-gn9kz
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"maistra.io/mesh-generation":"2.6.9-1-172"},"labels":{"app":"ig001","app.kubernetes.io/component":"istio-ingress","app.kubernetes.io/instance":"istio-system","app.kubernetes.io/managed-by":"maistra-istio-operator","app.kubernetes.io/name":"istio-ingress","app.kubernetes.io/part-of":"istio","app.kubernetes.io/version":"2.6.9-1-172","istio":"ingressgateway","istio.io/rev":"app-mesh-01","maistra-version":"2.6.9","maistra.io/owner":"istio-system","maistra.io/owner-name":"app-mesh-01","release":"istio"},"name":"ig001-service-account","namespace":"lbg-ocp-engineering-100-lab"}}

      '
    maistra.io/mesh-generation: 2.6.9-1-172
    meta.helm.sh/release-name: service-mesh-injected-gateway
    meta.helm.sh/release-namespace: istio-system
    openshift.io/internal-registry-pull-secret-ref: ig001-service-account-dockercfg-gn9kz
  creationTimestamp: '2025-09-17T08:27:25Z'
  labels:
    app: ig001
    app.kubernetes.io/component: istio-ingress
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: istio-ingress
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 2.6.9-1-234
    istio: ingressgateway
    istio.io/rev: app-mesh-01
    maistra-version: 2.6.9
    maistra.io/owner: istio-system
    maistra.io/owner-name: app-mesh-01
    release: istio
  name: ig001-service-account
  namespace: lbg-ocp-engineering-100-lab
  resourceVersion: '291679193'
  uid: 5a0dfa09-3d5c-4ca3-b8ff-86c715572b43
secrets:
- name: ig001-service-account-dockercfg-gn9kz
