apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ResourceQuota","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"namespace-definitions"},"name":"lbg-ocp-bookinfo-200-test-quota","namespace":"lbg-ocp-bookinfo-200-test"},"spec":{"hard":{"limits.cpu":"10","limits.memory":"12Gi","persistentvolumeclaims":"2","pods":10,"requests.cpu":"10","requests.memory":"12Gi","requests.storage":"2"}}}

      '
  creationTimestamp: '2025-08-22T09:29:09Z'
  labels:
    app.kubernetes.io/instance: namespace-definitions
  name: lbg-ocp-bookinfo-200-test-quota
  namespace: lbg-ocp-bookinfo-200-test
  resourceVersion: '291666996'
  uid: 9cb0881e-1456-4d47-87da-43fed7f7c870
spec:
  hard:
    limits.cpu: '32'
    limits.memory: 56Gi
    persistentvolumeclaims: '2'
    pods: '10'
    requests.cpu: '32'
    requests.memory: 56Gi
    requests.storage: '2'
status:
  hard:
    limits.cpu: '32'
    limits.memory: 56Gi
    persistentvolumeclaims: '2'
    pods: '10'
    requests.cpu: '32'
    requests.memory: 56Gi
    requests.storage: '2'
  used:
    limits.cpu: 1450m
    limits.memory: 2955925Ki
    persistentvolumeclaims: '0'
    pods: '8'
    requests.cpu: 1020m
    requests.memory: 1348245Ki
    requests.storage: '0'
