apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ResourceQuota","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"namespace-definitions"},"name":"lbg-ocp-injected-gw-400-lab-quota","namespace":"lbg-ocp-injected-gw-400-lab"},"spec":{"hard":{"limits.cpu":"10","limits.memory":"12Gi","persistentvolumeclaims":"2","pods":10,"requests.cpu":"10","requests.memory":"12Gi","requests.storage":"2"}}}

      '
  creationTimestamp: '2025-05-20T10:34:14Z'
  labels:
    app.kubernetes.io/instance: namespace-definitions
  name: lbg-ocp-injected-gw-400-lab-quota
  namespace: lbg-ocp-injected-gw-400-lab
  resourceVersion: '291667028'
  uid: 21ccb101-7920-45f3-8237-39c4829b0926
spec:
  hard:
    limits.cpu: '32'
    limits.memory: 56Gi
    persistentvolumeclaims: '2'
    pods: '10'
    requests.cpu: '32'
    requests.memory: 56Gi
    requests.storage: '2'
status:
  hard:
    limits.cpu: '32'
    limits.memory: 56Gi
    persistentvolumeclaims: '2'
    pods: '10'
    requests.cpu: '32'
    requests.memory: 56Gi
    requests.storage: '2'
  used:
    limits.cpu: 400m
    limits.memory: 400Mi
    persistentvolumeclaims: '0'
    pods: '2'
    requests.cpu: 300m
    requests.memory: 300Mi
    requests.storage: '0'
