apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ResourceQuota","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"namespace-definitions"},"name":"lbg-ocp-bookinfo-300-prod-quota","namespace":"lbg-ocp-bookinfo-300-prod"},"spec":{"hard":{"limits.cpu":"10","limits.memory":"12Gi","persistentvolumeclaims":"2","pods":10,"requests.cpu":"10","requests.memory":"12Gi","requests.storage":"2"}}}

      '
  creationTimestamp: '2025-05-19T20:38:19Z'
  labels:
    app.kubernetes.io/instance: namespace-definitions
  name: lbg-ocp-bookinfo-300-prod-quota
  namespace: lbg-ocp-bookinfo-300-prod
  resourceVersion: '291667013'
  uid: 84d1d6d4-320d-421b-b7d0-fef1b2073e03
spec:
  hard:
    limits.cpu: '32'
    limits.memory: 56Gi
    persistentvolumeclaims: '2'
    pods: '10'
    requests.cpu: '32'
    requests.memory: 56Gi
    requests.storage: '2'
status:
  hard:
    limits.cpu: '32'
    limits.memory: 56Gi
    persistentvolumeclaims: '2'
    pods: '10'
    requests.cpu: '32'
    requests.memory: 56Gi
    requests.storage: '2'
  used:
    limits.cpu: 400m
    limits.memory: 400Mi
    persistentvolumeclaims: '0'
    pods: '2'
    requests.cpu: 300m
    requests.memory: 300Mi
    requests.storage: '0'
