project:
#------------------------------------
- namespace: lbg-ocp-engineering-100-lab
  egress:
    id: '001'
    enabled: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  ingress:
    id: '001'
    enabled: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  labels:
    snow: IT.OCP.CLOUD.LAB
    cmdb_appid: AL12345
    cluster: ocp.cloud.lab
    argo:
      enabled: true
      managed_by: openshift-gitops
    ad_group:
      enabled: true
      name: GG_OCP_CLOUD_LAB_GROUP
      view: GG_OCP_CLOUD_LAB
    portworx:
      enabled: false
  annotations:
    contact: aiyaz.khan
    openshift:
      description: Engineering namespace
      display_name: Engineering namespace
      node_selector: node-role.kubernetes.io/app=
  pods: 10
  limits:
    cpu: 10
    memory: 12Gi
  requests:
    cpu: 10
    memory: 12Gi
    storage: 2
  persistentvolumeclaims: 2
#------------------------------------
- namespace: lbg-ocp-bookinfo-200-test
  egress:
    id: '002'
    enabled: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  ingress:
    id: '002'
    enabled: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  labels:
    snow: IT.OCP.CLOUD.LAB
    cmdb_appid: AL10432
    cluster: ocp.cloud.lab
    argo:
      enabled: true
      managed_by: openshift-gitops
    ad_group:
      enabled: true
      name: GG_OCP_CLOUD_LAB_GROUP
      view: GG_OCP_CLOUD_LAB
    portworx:
      enabled: false
  annotations:
    contact: aiyaz.khan
    openshift:
      description: Engineering namespace
      display_name: Engineering namespace
      node_selector: node-role.kubernetes.io/app=
  pods: 10
  limits:
    cpu: 10
    memory: 12Gi
  requests:
    cpu: 10
    memory: 12Gi
    storage: 2
  persistentvolumeclaims: 2
#------------------------------------
- namespace: lbg-ocp-bookinfo-300-prod
  egress:
    id: '003'
    enabled: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  ingress:
    id: '003'
    enabled: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  labels:
    snow: IT.OCP.CLOUD.LAB
    cmdb_appid: AL10432
    cluster: ocp.cloud.lab
    argo:
      enabled: true
      managed_by: openshift-gitops
    ad_group:
      enabled: true
      name: GG_OCP_CLOUD_LAB_GROUP
      view: GG_OCP_CLOUD_LAB
    portworx:
      enabled: false
  annotations:
    contact: aiyaz.khan
    openshift:
      description: Engineering namespace
      display_name: Engineering namespace
      node_selector: node-role.kubernetes.io/app=
  pods: 10
  limits:
    cpu: 10
    memory: 12Gi
  requests:
    cpu: 10
    memory: 12Gi
    storage: 2
  persistentvolumeclaims: 2
#------------------------------------
- namespace: lbg-ocp-injected-gw-400-lab
  egress:
    id: '004'
    enabled: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  ingress:
    id: '004'
    enabled: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  labels:
    snow: IT.OCP.CLOUD.LAB
    cmdb_appid: AL10432
    cluster: ocp.cloud.lab
    argo:
      enabled: true
      managed_by: openshift-gitops
    ad_group:
      enabled: true
      name: GG_OCP_CLOUD_LAB_GROUP
      view: GG_OCP_CLOUD_LAB
    portworx:
      enabled: false
  annotations:
    contact: aiyaz.khan
    openshift:
      description: Engineering namespace
      display_name: Engineering namespace
      node_selector: node-role.kubernetes.io/app=
  pods: 10
  limits:
    cpu: 10
    memory: 12Gi
  requests:
    cpu: 10
    memory: 12Gi
    storage: 2
  persistentvolumeclaims: 2
#------------------------------------
- namespace: lbg-ocp-servicemesh-3-400-lab
  egress:
    id: '005'
    enabled: false
    injected_egress: true
    create_service: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  ingress:
    id: '005'
    enabled: false
    injected_ingress: true
    create_service: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  labels:
    snow: IT.OCP.CLOUD.LAB
    cmdb_appid: AL10432
    cluster: ocp.cloud.lab
    argo:
      enabled: true
      managed_by: openshift-gitops
    ad_group:
      enabled: true
      name: GG_OCP_CLOUD_LAB_GROUP
      view: GG_OCP_CLOUD_LAB
    portworx:
      enabled: false
  annotations:
    contact: aiyaz.khan
    openshift:
      description: Engineering namespace
      display_name: Engineering namespace
      node_selector: node-role.kubernetes.io/app=
  pods: 10
  limits:
    cpu: 10
    memory: 12Gi
  requests:
    cpu: 10
    memory: 12Gi
    storage: 2
  persistentvolumeclaims: 2
#------------------------------------
- namespace: lbg-ocp-meshtest-309-lab
  egress:
    id: '006'
    enabled: false
    injected_egress: true
    create_service: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  ingress:
    id: '006'
    enabled: false
    injected_ingress: true
    create_service: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  labels:
    snow: IT.OCP.CLOUD.LAB
    cmdb_appid: AL10432
    cluster: ocp.cloud.lab
    argo:
      enabled: true
      managed_by: openshift-gitops
    ad_group:
      enabled: true
      name: GG_OCP_CLOUD_LAB_GROUP
      view: GG_OCP_CLOUD_LAB
    portworx:
      enabled: false
  annotations:
    contact: aiyaz.khan
    openshift:
      description: Engineering namespace
      display_name: Engineering namespace
      node_selector: node-role.kubernetes.io/app=
  pods: 10
  limits:
    cpu: 10
    memory: 12Gi
  requests:
    cpu: 10
    memory: 12Gi
    storage: 2
  persistentvolumeclaims: 2
#------------------------------------
- namespace: lbg-ocp-engineering-redsquad-309-lab
  egress:
    id: '007'
    enabled: false
    injected_egress: true
    create_service: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  ingress:
    id: '007'
    enabled: false
    injected_ingress: true
    create_service: true
    replicas: 1
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 150Mi
  labels:
    snow: IT.OCP.CLOUD.LAB
    cmdb_appid: AL10432
    cluster: ocp.cloud.lab
    argo:
      enabled: true
      managed_by: openshift-gitops
    ad_group:
      enabled: true
      name: GG_OCP_CLOUD_LAB_GROUP
      view: GG_OCP_CLOUD_LAB
    portworx:
      enabled: false
  annotations:
    contact: aiyaz.khan
    openshift:
      description: Engineering namespace
      display_name: Engineering namespace
      node_selector: node-role.kubernetes.io/app=
  pods: 10
  limits:
    cpu: 10
    memory: 12Gi
  requests:
    cpu: 10
    memory: 12Gi
    storage: 2
  persistentvolumeclaims: 2
